# Generated by Django 5.2.5 on 2025-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('used_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
