# Generated by Django 5.2.5 on 2025-09-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parents',
            new_name='parent',
        ),
    ]
