# Generated by Django 5.2.5 on 2025-08-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='palce',
            new_name='place',
        ),
    ]
